### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by tobias-kirschstein** [Cryptiex/3D-FaceReconstruction#8]
- [x] Plot fitted shape and expression coefficients as bar chart + Combine frame with/without mask + reconstruction error
- [x] Plot error between depth map and reconstruction
- [x] Visualize single optimization step as video
- [x] Loss plot Quaternion vs Lie
- [x] Only Dense Reconstruction

**Comment by huberl** [comment]
I'm on it
